-- All of them have the same password: testing
INSERT INTO company (company_name, email, password, contact, address, description, website, logo_url, is_email_verified, sector, created_at) 
VALUES 
('DZ Technologies', 'contact@dztech.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 23 45 67 89', '123 Rue Didouche Mourad, Algiers', 'Leading Algerian software development company specializing in custom solutions.', 'https://dztech.dz', NULL, true, 'Information Technology', NOW()),
('Algeria Telecom', 'recruitment@telecom.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 98 76 54', 'Algiers Telecom Center, Algiers', 'National telecommunications operator providing various IT services.', 'https://telecom.dz', NULL, true, 'Telecommunications', NOW()),
('Sonatrach', 'careers@sonatrach.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 23 45 67', 'Hydra, Algiers', 'Algerian state-owned oil company with digital transformation initiatives.', 'https://sonatrach.dz', NULL, true, 'Oil & Gas', NOW()),
('Ooredoo Algeria', 'jobs@ooredoo.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 89 01 23', 'Bab Ezzouar, Algiers', 'Telecommunications provider offering various IT and digital roles.', 'https://ooredoo.dz', NULL, true, 'Telecommunications', NOW()),
('CEVITAL', 'hr@cevital.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 24 56 78 90', 'Boumerdes Industrial Zone', 'Algerian conglomerate with IT department for enterprise systems.', 'https://cevital.dz', NULL, true, 'Conglomerate', NOW()),
('BNA (Banque Nationale d''Algérie)', 'recrutement@bna.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 34 56 78', 'Place Audin, Algiers', 'National bank of Algeria with digital banking initiatives.', 'https://bna.dz', NULL, true, 'Banking & Finance', NOW()),
('ENIE (Entreprise Nationale des Industries Électroniques)', 'contact@enie.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 25 67 89 01', 'Sidi Bel Abbès', 'National electronics company with software development division.', 'https://enie.dz', NULL, true, 'Electronics', NOW()),
('Algérie Poste', 'emploi@poste.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 90 12 34', 'Algiers Central Post Office', 'Postal service with digital transformation projects.', 'https://poste.dz', NULL, true, 'Logistics & Postal Services', NOW()),
('Djezzy', 'careers@djezzy.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 78 90 12', 'Baba Hassen, Algiers', 'Mobile telecommunications operator.', 'https://djezzy.dz', NULL, true, 'Telecommunications', NOW()),
('COSIDER', 'rh@cosider.dz', '$2b$12$Gbl8zIsZCR9LHXBgCdjBZ.IVkATUArxIL4JqpG7nynP7Gr1hhrkkO', '+213 21 45 67 89', 'Les Sources, Ben Aknoun, Algiers', 'Engineering and construction company with IT infrastructure needs.', 'https://cosider.dz', NULL, true, 'Construction & Engineering', NOW())
ON CONFLICT (email) DO NOTHING;