"""Add purpose field to OTP table

Revision ID: 41e30682aeb4
Revises: 
Create Date: 2025-12-24 00:00:00.100966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e30682aeb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('purpose', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_otp_purpose'), 'otp', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_purpose'), table_name='otp')
    op.drop_column('otp', 'purpose')
    # ### end Alembic commands ###
