"""add_application_constraints_and_relationships

Revision ID: 49d1f32e4668
Revises: 41e30682aeb4
Create Date: 2025-12-31 06:21:02.833708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d1f32e4668'
down_revision: Union[str, None] = '41e30682aeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('views_count', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('applications_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'applications_count')
    op.drop_column('offer', 'views_count')
    # ### end Alembic commands ###
